name: littardo
description: Shopping UI design in Flutter

version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  country_pickers: ^1.1.0
  flutter_icons: ^0.2.5
  fancy_bottom_navigation: ^0.3.2
  carousel_slider: ^1.3.0
  division: ^0.6.1
  page_transition: '^1.1.0'
  bottom_navy_bar: ^5.1.0
  sliding_up_panel: ^0.3.4
  flutter_xlider: ^2.5.1
  intro_views_flutter: ^2.6.0
  rflutter_alert: ^1.0.3
  hidden_drawer_menu: ^1.1.2
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.4+6
  http: ^0.12.0+2
  toast: ^0.1.5
  badges: ^1.1.0
  provider: null
  lazy_load_scrollview: 1.0.1
  url_launcher: 4.0.0
  flutter_share_me: ^0.9.1
  flutter_launcher_icons: "^0.7.3"
  animated_splash: ^1.0.0
  flutter_rating_bar: ^3.0.1+1
  lottie: ^0.2.2
  # firebase_messaging: ^6.0.13
  device_info: ^0.4.2+4
  geocoder: ^0.2.1
  google_maps_flutter: ^0.5.31
  geolocator: ^5.1.5
  photo_view: ^0.9.2
  intent: ^1.1.0
  path_drawing: ^0.2.3
  dropdown_search: ^0.4.4
  razorpay_flutter: ^1.2.2
  fluttertoast: ^7.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/littardo_logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat.ttf

